/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ServiceInterest = IDL.Variant({
  'strategyConsulting' : IDL.Null,
  'other' : IDL.Null,
  'publicRelations' : IDL.Null,
  'eventManagement' : IDL.Null,
  'mediaProduction' : IDL.Null,
  'digitalMarketing' : IDL.Null,
  'influencerMarketing' : IDL.Null,
  'contentCreation' : IDL.Null,
});
export const Time = IDL.Int;
export const PhoneNumber = IDL.Record({
  'countryCode' : IDL.Text,
  'number' : IDL.Text,
});
export const Inquiry = IDL.Record({
  'id' : IDL.Nat,
  'fullName' : IDL.Text,
  'submittedBy' : IDL.Principal,
  'email' : IDL.Text,
  'serviceInterest' : ServiceInterest,
  'message' : IDL.Text,
  'timestamp' : Time,
  'consentGiven' : IDL.Bool,
  'phone' : IDL.Opt(PhoneNumber),
});

export const idlService = IDL.Service({
  'getInquiry' : IDL.Func([IDL.Nat], [Inquiry], ['query']),
  'listInquiries' : IDL.Func([], [IDL.Vec(Inquiry)], ['query']),
  'submitInquiry' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Opt(PhoneNumber),
        ServiceInterest,
        IDL.Text,
        IDL.Bool,
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ServiceInterest = IDL.Variant({
    'strategyConsulting' : IDL.Null,
    'other' : IDL.Null,
    'publicRelations' : IDL.Null,
    'eventManagement' : IDL.Null,
    'mediaProduction' : IDL.Null,
    'digitalMarketing' : IDL.Null,
    'influencerMarketing' : IDL.Null,
    'contentCreation' : IDL.Null,
  });
  const Time = IDL.Int;
  const PhoneNumber = IDL.Record({
    'countryCode' : IDL.Text,
    'number' : IDL.Text,
  });
  const Inquiry = IDL.Record({
    'id' : IDL.Nat,
    'fullName' : IDL.Text,
    'submittedBy' : IDL.Principal,
    'email' : IDL.Text,
    'serviceInterest' : ServiceInterest,
    'message' : IDL.Text,
    'timestamp' : Time,
    'consentGiven' : IDL.Bool,
    'phone' : IDL.Opt(PhoneNumber),
  });
  
  return IDL.Service({
    'getInquiry' : IDL.Func([IDL.Nat], [Inquiry], ['query']),
    'listInquiries' : IDL.Func([], [IDL.Vec(Inquiry)], ['query']),
    'submitInquiry' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Opt(PhoneNumber),
          ServiceInterest,
          IDL.Text,
          IDL.Bool,
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };