/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Inquiry {
  'id' : bigint,
  'fullName' : string,
  'submittedBy' : Principal,
  'email' : string,
  'serviceInterest' : ServiceInterest,
  'message' : string,
  'timestamp' : Time,
  'consentGiven' : boolean,
  'phone' : [] | [PhoneNumber],
}
export interface PhoneNumber { 'countryCode' : string, 'number' : string }
export type ServiceInterest = { 'strategyConsulting' : null } |
  { 'other' : null } |
  { 'publicRelations' : null } |
  { 'eventManagement' : null } |
  { 'mediaProduction' : null } |
  { 'digitalMarketing' : null } |
  { 'influencerMarketing' : null } |
  { 'contentCreation' : null };
export type Time = bigint;
export interface _SERVICE {
  'getInquiry' : ActorMethod<[bigint], Inquiry>,
  'listInquiries' : ActorMethod<[], Array<Inquiry>>,
  'submitInquiry' : ActorMethod<
    [string, string, [] | [PhoneNumber], ServiceInterest, string, boolean],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];