/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface PhoneNumber {
    countryCode: string;
    number: string;
}
export type Time = bigint;
export interface Inquiry {
    id: bigint;
    fullName: string;
    submittedBy: Principal;
    email: string;
    serviceInterest: ServiceInterest;
    message: string;
    timestamp: Time;
    consentGiven: boolean;
    phone?: PhoneNumber;
}
export enum ServiceInterest {
    strategyConsulting = "strategyConsulting",
    other = "other",
    publicRelations = "publicRelations",
    eventManagement = "eventManagement",
    mediaProduction = "mediaProduction",
    digitalMarketing = "digitalMarketing",
    influencerMarketing = "influencerMarketing",
    contentCreation = "contentCreation"
}
export interface backendInterface {
    getInquiry(id: bigint): Promise<Inquiry>;
    listInquiries(): Promise<Array<Inquiry>>;
    submitInquiry(fullName: string, email: string, phone: PhoneNumber | null, serviceInterest: ServiceInterest, message: string, consentGiven: boolean): Promise<void>;
}
import type { Inquiry as _Inquiry, PhoneNumber as _PhoneNumber, ServiceInterest as _ServiceInterest, Time as _Time } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async getInquiry(arg0: bigint): Promise<Inquiry> {
        if (this.processError) {
            try {
                const result = await this.actor.getInquiry(arg0);
                return from_candid_Inquiry_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInquiry(arg0);
            return from_candid_Inquiry_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async listInquiries(): Promise<Array<Inquiry>> {
        if (this.processError) {
            try {
                const result = await this.actor.listInquiries();
                return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listInquiries();
            return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async submitInquiry(arg0: string, arg1: string, arg2: PhoneNumber | null, arg3: ServiceInterest, arg4: string, arg5: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitInquiry(arg0, arg1, to_candid_opt_n7(this._uploadFile, this._downloadFile, arg2), to_candid_ServiceInterest_n8(this._uploadFile, this._downloadFile, arg3), arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitInquiry(arg0, arg1, to_candid_opt_n7(this._uploadFile, this._downloadFile, arg2), to_candid_ServiceInterest_n8(this._uploadFile, this._downloadFile, arg3), arg4, arg5);
            return result;
        }
    }
}
function from_candid_Inquiry_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Inquiry): Inquiry {
    return from_candid_record_n2(_uploadFile, _downloadFile, value);
}
function from_candid_ServiceInterest_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ServiceInterest): ServiceInterest {
    return from_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PhoneNumber]): PhoneNumber | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    fullName: string;
    submittedBy: Principal;
    email: string;
    serviceInterest: _ServiceInterest;
    message: string;
    timestamp: _Time;
    consentGiven: boolean;
    phone: [] | [_PhoneNumber];
}): {
    id: bigint;
    fullName: string;
    submittedBy: Principal;
    email: string;
    serviceInterest: ServiceInterest;
    message: string;
    timestamp: Time;
    consentGiven: boolean;
    phone?: PhoneNumber;
} {
    return {
        id: value.id,
        fullName: value.fullName,
        submittedBy: value.submittedBy,
        email: value.email,
        serviceInterest: from_candid_ServiceInterest_n3(_uploadFile, _downloadFile, value.serviceInterest),
        message: value.message,
        timestamp: value.timestamp,
        consentGiven: value.consentGiven,
        phone: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.phone))
    };
}
function from_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    strategyConsulting: null;
} | {
    other: null;
} | {
    publicRelations: null;
} | {
    eventManagement: null;
} | {
    mediaProduction: null;
} | {
    digitalMarketing: null;
} | {
    influencerMarketing: null;
} | {
    contentCreation: null;
}): ServiceInterest {
    return "strategyConsulting" in value ? ServiceInterest.strategyConsulting : "other" in value ? ServiceInterest.other : "publicRelations" in value ? ServiceInterest.publicRelations : "eventManagement" in value ? ServiceInterest.eventManagement : "mediaProduction" in value ? ServiceInterest.mediaProduction : "digitalMarketing" in value ? ServiceInterest.digitalMarketing : "influencerMarketing" in value ? ServiceInterest.influencerMarketing : "contentCreation" in value ? ServiceInterest.contentCreation : value;
}
function from_candid_vec_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Inquiry>): Array<Inquiry> {
    return value.map((x)=>from_candid_Inquiry_n1(_uploadFile, _downloadFile, x));
}
function to_candid_ServiceInterest_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ServiceInterest): _ServiceInterest {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PhoneNumber | null): [] | [_PhoneNumber] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ServiceInterest): {
    strategyConsulting: null;
} | {
    other: null;
} | {
    publicRelations: null;
} | {
    eventManagement: null;
} | {
    mediaProduction: null;
} | {
    digitalMarketing: null;
} | {
    influencerMarketing: null;
} | {
    contentCreation: null;
} {
    return value == ServiceInterest.strategyConsulting ? {
        strategyConsulting: null
    } : value == ServiceInterest.other ? {
        other: null
    } : value == ServiceInterest.publicRelations ? {
        publicRelations: null
    } : value == ServiceInterest.eventManagement ? {
        eventManagement: null
    } : value == ServiceInterest.mediaProduction ? {
        mediaProduction: null
    } : value == ServiceInterest.digitalMarketing ? {
        digitalMarketing: null
    } : value == ServiceInterest.influencerMarketing ? {
        influencerMarketing: null
    } : value == ServiceInterest.contentCreation ? {
        contentCreation: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
